apiVersion: v1
kind: Namespace
metadata:
  name: hexwar-infra
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-service
  namespace: hexwar-infra
spec:
  clusterIP: None # Headless Service
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  - port: 16379
    targetPort: 16379
    name: cluster-bus
  selector:
    app: redis-cluster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: hexwar-infra
spec:
  serviceName: redis-cluster-service
  replicas: 6
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        command:
        - "redis-server"
        - "--cluster-enabled"
        - "yes"
        - "--cluster-config-file"
        - "nodes.conf"
        - "--cluster-node-timeout"
        - "5000"
        - "--appendonly"
        - "yes"
        - "--port"
        - "6379"
        ports:
        - containerPort: 6379
          name: redis
        - containerPort: 16379
          name: cluster-bus
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cluster-init
  namespace: hexwar-infra
spec:
  template:
    spec:
      containers:
      - name: redis-init
        image: redis:7-alpine
        command:
        - "sh"
        - "-c"
        - |
          # Redis Pod들이 정상 부팅되고 DNS 조회가 될 때까지 15초 대기합니다.
          sleep 15;
          echo "yes" | redis-cli --cluster create \
            redis-cluster-0.redis-cluster-service.hexwar-infra.svc.cluster.local:6379 \
            redis-cluster-1.redis-cluster-service.hexwar-infra.svc.cluster.local:6379 \
            redis-cluster-2.redis-cluster-service.hexwar-infra.svc.cluster.local:6379 \
            redis-cluster-3.redis-cluster-service.hexwar-infra.svc.cluster.local:6379 \
            redis-cluster-4.redis-cluster-service.hexwar-infra.svc.cluster.local:6379 \
            redis-cluster-5.redis-cluster-service.hexwar-infra.svc.cluster.local:6379 \
            --cluster-replicas 1
      restartPolicy: OnFailure
